// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFkFYCfP0CYl9-HrhdlsrMdpVyIUhmwYU',
    appId: '1:1074723574034:web:c9ce144260e5070072a3cb',
    messagingSenderId: '1074723574034',
    projectId: 'crudfirebase-50e28',
    authDomain: 'crudfirebase-50e28.firebaseapp.com',
    storageBucket: 'crudfirebase-50e28.appspot.com',
    measurementId: 'G-8QQXHEB42E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-Z0-ZTfQqCA7IgA2YmBViwxLBLJg0NA',
    appId: '1:1074723574034:android:df04d5e823b699ad72a3cb',
    messagingSenderId: '1074723574034',
    projectId: 'crudfirebase-50e28',
    storageBucket: 'crudfirebase-50e28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSZ4dB0fT0VlzNylxUAuboXioeAgvaIWg',
    appId: '1:1074723574034:ios:1dad3e229bc38e0172a3cb',
    messagingSenderId: '1074723574034',
    projectId: 'crudfirebase-50e28',
    storageBucket: 'crudfirebase-50e28.appspot.com',
    iosBundleId: 'com.example.flutterapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSZ4dB0fT0VlzNylxUAuboXioeAgvaIWg',
    appId: '1:1074723574034:ios:1dad3e229bc38e0172a3cb',
    messagingSenderId: '1074723574034',
    projectId: 'crudfirebase-50e28',
    storageBucket: 'crudfirebase-50e28.appspot.com',
    iosBundleId: 'com.example.flutterapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFkFYCfP0CYl9-HrhdlsrMdpVyIUhmwYU',
    appId: '1:1074723574034:web:8a7af504e172187172a3cb',
    messagingSenderId: '1074723574034',
    projectId: 'crudfirebase-50e28',
    authDomain: 'crudfirebase-50e28.firebaseapp.com',
    storageBucket: 'crudfirebase-50e28.appspot.com',
    measurementId: 'G-LH1Q0G87JS',
  );
}
